Add new API specs for updating Webhook subscriptions
affinity/slate pull request #57
Opened 2021-05-04 19:32 UTC by yadwinder11

**Asana Task**: https://app.asana.com/0/1199933461955492/1200272129615846/f

## Description
The PR includes the following changes to our API Docs
- Return subscription status as a response of `GET` and `POST` call
- New API `PUT` to update the existing subscription

![Screen Shot 2021-05-04 at 3 32 44 PM](https://user-images.githubusercontent.com/79168430/117059601-face9000-aced-11eb-8bbf-184cb8c81a24.png)

2021-05-04 23:16 UTC, collinsauve approved these changes

2021-05-05 00:15 UTC, mimslee32 requested changes

2021-05-05 00:15 UTC, mimslee32 commented on source/includes/_webhooks.md
> +| disabled      | boolean  | If the subscription is disabled, this is true. Otherwise, this is false. |
`False by default. A subscription may be disabled automatically if ..... or manually.` <- maybe something like that would be more helpful

2021-05-05 00:15 UTC, mimslee32 commented on source/includes/_webhooks.md
> +| disabled      | boolean  | false    | Change the status of a subscription. To enable a subscription, provide the value as `true`. Otherwise, provide the value as `false.` |
Isn't it the opposite? Don't we want `disabled=false` to enable the subscription?

2021-05-05 13:24 UTC, yadwinder11 commented on source/includes/_webhooks.md
> +| disabled      | boolean  | false    | Change the status of a subscription. To enable a subscription, provide the value as `true`. Otherwise, provide the value as `false.` |
You are right, Good Catch :)

2021-05-05 18:13 UTC, mimslee32 approved these changes
🚢

2021-05-05 19:49 UTC, merged